# Generated by Django 2.2.9 on 2020-02-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytsmovie',
            name='movie_data',
        ),
    ]
